# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pack_dc_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PackDCWindow(object):
    def setupUi(self, PackDCWindow):
        PackDCWindow.setObjectName(_fromUtf8("PackDCWindow"))
        PackDCWindow.resize(667, 1874)
        self.centralwidget = QtGui.QWidget(PackDCWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.op_combo = QtGui.QComboBox(self.frame)
        self.op_combo.setObjectName(_fromUtf8("op_combo"))
        self.horizontalLayout_5.addWidget(self.op_combo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.workflow_combo = QtGui.QComboBox(self.frame)
        self.workflow_combo.setObjectName(_fromUtf8("workflow_combo"))
        self.horizontalLayout.addWidget(self.workflow_combo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.frame_valid_zero_eone = QtGui.QFrame(self.centralwidget)
        self.frame_valid_zero_eone.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_valid_zero_eone.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_valid_zero_eone.setObjectName(_fromUtf8("frame_valid_zero_eone"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_valid_zero_eone)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame1_assignation = QtGui.QCheckBox(self.frame_valid_zero_eone)
        self.frame1_assignation.setObjectName(_fromUtf8("frame1_assignation"))
        self.gridLayout.addWidget(self.frame1_assignation, 8, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.frame_valid_zero_eone)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame1_ordre = QtGui.QCheckBox(self.groupBox)
        self.frame1_ordre.setObjectName(_fromUtf8("frame1_ordre"))
        self.verticalLayout_5.addWidget(self.frame1_ordre)
        self.frame1_peak = QtGui.QCheckBox(self.groupBox)
        self.frame1_peak.setObjectName(_fromUtf8("frame1_peak"))
        self.verticalLayout_5.addWidget(self.frame1_peak)
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 1)
        self.frame1_24 = QtGui.QCheckBox(self.frame_valid_zero_eone)
        self.frame1_24.setObjectName(_fromUtf8("frame1_24"))
        self.gridLayout.addWidget(self.frame1_24, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.frame_valid_zero_eone)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame1_titre = QtGui.QCheckBox(self.groupBox_3)
        self.frame1_titre.setObjectName(_fromUtf8("frame1_titre"))
        self.verticalLayout_7.addWidget(self.frame1_titre)
        self.frame1_ratio = QtGui.QCheckBox(self.groupBox_3)
        self.frame1_ratio.setObjectName(_fromUtf8("frame1_ratio"))
        self.verticalLayout_7.addWidget(self.frame1_ratio)
        self.frame1_framerate = QtGui.QCheckBox(self.groupBox_3)
        self.frame1_framerate.setObjectName(_fromUtf8("frame1_framerate"))
        self.verticalLayout_7.addWidget(self.frame1_framerate)
        self.frame1_audio = QtGui.QCheckBox(self.groupBox_3)
        self.frame1_audio.setObjectName(_fromUtf8("frame1_audio"))
        self.verticalLayout_7.addWidget(self.frame1_audio)
        self.frame1_mixes = QtGui.QCheckBox(self.groupBox_3)
        self.frame1_mixes.setObjectName(_fromUtf8("frame1_mixes"))
        self.verticalLayout_7.addWidget(self.frame1_mixes)
        self.frame1_subs = QtGui.QCheckBox(self.groupBox_3)
        self.frame1_subs.setObjectName(_fromUtf8("frame1_subs"))
        self.verticalLayout_7.addWidget(self.frame1_subs)
        self.frame1_version = QtGui.QCheckBox(self.groupBox_3)
        self.frame1_version.setObjectName(_fromUtf8("frame1_version"))
        self.verticalLayout_7.addWidget(self.frame1_version)
        self.gridLayout.addWidget(self.groupBox_3, 9, 0, 1, 1)
        self.frame1_prores = QtGui.QCheckBox(self.frame_valid_zero_eone)
        self.frame1_prores.setObjectName(_fromUtf8("frame1_prores"))
        self.gridLayout.addWidget(self.frame1_prores, 0, 0, 1, 1)
        self.frame1_tc = QtGui.QCheckBox(self.frame_valid_zero_eone)
        self.frame1_tc.setObjectName(_fromUtf8("frame1_tc"))
        self.gridLayout.addWidget(self.frame1_tc, 7, 0, 1, 1)
        self.frame1_mono = QtGui.QCheckBox(self.frame_valid_zero_eone)
        self.frame1_mono.setObjectName(_fromUtf8("frame1_mono"))
        self.gridLayout.addWidget(self.frame1_mono, 3, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_valid_zero_eone)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame1_valeurs = QtGui.QCheckBox(self.groupBox_2)
        self.frame1_valeurs.setObjectName(_fromUtf8("frame1_valeurs"))
        self.verticalLayout_6.addWidget(self.frame1_valeurs)
        self.frame1_colo = QtGui.QCheckBox(self.groupBox_2)
        self.frame1_colo.setObjectName(_fromUtf8("frame1_colo"))
        self.verticalLayout_6.addWidget(self.frame1_colo)
        self.gridLayout.addWidget(self.groupBox_2, 6, 0, 1, 1)
        self.frame1_23 = QtGui.QCheckBox(self.frame_valid_zero_eone)
        self.frame1_23.setObjectName(_fromUtf8("frame1_23"))
        self.gridLayout.addWidget(self.frame1_23, 2, 0, 1, 1)
        self.frame1_jes = QtGui.QCheckBox(self.frame_valid_zero_eone)
        self.frame1_jes.setObjectName(_fromUtf8("frame1_jes"))
        self.gridLayout.addWidget(self.frame1_jes, 4, 0, 1, 1)
        self.frame1_prequal = QtGui.QCheckBox(self.frame_valid_zero_eone)
        self.frame1_prequal.setObjectName(_fromUtf8("frame1_prequal"))
        self.gridLayout.addWidget(self.frame1_prequal, 10, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame_valid_zero_eone)
        self.frame_valid_lib = QtGui.QFrame(self.centralwidget)
        self.frame_valid_lib.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_valid_lib.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_valid_lib.setObjectName(_fromUtf8("frame_valid_lib"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_valid_lib)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame2_prores = QtGui.QCheckBox(self.frame_valid_lib)
        self.frame2_prores.setObjectName(_fromUtf8("frame2_prores"))
        self.gridLayout_2.addWidget(self.frame2_prores, 0, 0, 1, 1)
        self.frame2_24 = QtGui.QCheckBox(self.frame_valid_lib)
        self.frame2_24.setObjectName(_fromUtf8("frame2_24"))
        self.gridLayout_2.addWidget(self.frame2_24, 1, 0, 1, 1)
        self.frame2_tc = QtGui.QCheckBox(self.frame_valid_lib)
        self.frame2_tc.setObjectName(_fromUtf8("frame2_tc"))
        self.gridLayout_2.addWidget(self.frame2_tc, 4, 0, 1, 1)
        self.frame2_jes = QtGui.QCheckBox(self.frame_valid_lib)
        self.frame2_jes.setObjectName(_fromUtf8("frame2_jes"))
        self.gridLayout_2.addWidget(self.frame2_jes, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.frame_valid_lib)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.frame2_ordre = QtGui.QCheckBox(self.groupBox_4)
        self.frame2_ordre.setObjectName(_fromUtf8("frame2_ordre"))
        self.verticalLayout_9.addWidget(self.frame2_ordre)
        self.frame2_peak = QtGui.QCheckBox(self.groupBox_4)
        self.frame2_peak.setObjectName(_fromUtf8("frame2_peak"))
        self.verticalLayout_9.addWidget(self.frame2_peak)
        self.gridLayout_2.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.frame2_assignation = QtGui.QCheckBox(self.frame_valid_lib)
        self.frame2_assignation.setObjectName(_fromUtf8("frame2_assignation"))
        self.gridLayout_2.addWidget(self.frame2_assignation, 5, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.frame_valid_lib)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.frame2_titre = QtGui.QCheckBox(self.groupBox_5)
        self.frame2_titre.setObjectName(_fromUtf8("frame2_titre"))
        self.verticalLayout_10.addWidget(self.frame2_titre)
        self.frame2_lib = QtGui.QCheckBox(self.groupBox_5)
        self.frame2_lib.setObjectName(_fromUtf8("frame2_lib"))
        self.verticalLayout_10.addWidget(self.frame2_lib)
        self.frame2_ratio = QtGui.QCheckBox(self.groupBox_5)
        self.frame2_ratio.setObjectName(_fromUtf8("frame2_ratio"))
        self.verticalLayout_10.addWidget(self.frame2_ratio)
        self.frame2_framerate = QtGui.QCheckBox(self.groupBox_5)
        self.frame2_framerate.setObjectName(_fromUtf8("frame2_framerate"))
        self.verticalLayout_10.addWidget(self.frame2_framerate)
        self.frame2_audio = QtGui.QCheckBox(self.groupBox_5)
        self.frame2_audio.setObjectName(_fromUtf8("frame2_audio"))
        self.verticalLayout_10.addWidget(self.frame2_audio)
        self.frame2_mixes = QtGui.QCheckBox(self.groupBox_5)
        self.frame2_mixes.setObjectName(_fromUtf8("frame2_mixes"))
        self.verticalLayout_10.addWidget(self.frame2_mixes)
        self.frame2_subs = QtGui.QCheckBox(self.groupBox_5)
        self.frame2_subs.setObjectName(_fromUtf8("frame2_subs"))
        self.verticalLayout_10.addWidget(self.frame2_subs)
        self.gridLayout_2.addWidget(self.groupBox_5, 6, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.frame_valid_lib)
        self.frame_valid_vod = QtGui.QFrame(self.centralwidget)
        self.frame_valid_vod.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_valid_vod.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_valid_vod.setObjectName(_fromUtf8("frame_valid_vod"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_valid_vod)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame3_tc = QtGui.QCheckBox(self.frame_valid_vod)
        self.frame3_tc.setObjectName(_fromUtf8("frame3_tc"))
        self.gridLayout_3.addWidget(self.frame3_tc, 5, 0, 1, 1)
        self.frame3_mono = QtGui.QCheckBox(self.frame_valid_vod)
        self.frame3_mono.setObjectName(_fromUtf8("frame3_mono"))
        self.gridLayout_3.addWidget(self.frame3_mono, 2, 0, 1, 1)
        self.frame3_24 = QtGui.QCheckBox(self.frame_valid_vod)
        self.frame3_24.setObjectName(_fromUtf8("frame3_24"))
        self.gridLayout_3.addWidget(self.frame3_24, 1, 0, 1, 1)
        self.frame3_prores = QtGui.QCheckBox(self.frame_valid_vod)
        self.frame3_prores.setObjectName(_fromUtf8("frame3_prores"))
        self.gridLayout_3.addWidget(self.frame3_prores, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.frame_valid_vod)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.frame3_ordre = QtGui.QCheckBox(self.groupBox_6)
        self.frame3_ordre.setObjectName(_fromUtf8("frame3_ordre"))
        self.verticalLayout_12.addWidget(self.frame3_ordre)
        self.frame3_peak = QtGui.QCheckBox(self.groupBox_6)
        self.frame3_peak.setObjectName(_fromUtf8("frame3_peak"))
        self.verticalLayout_12.addWidget(self.frame3_peak)
        self.gridLayout_3.addWidget(self.groupBox_6, 4, 0, 1, 1)
        self.frame3_jes = QtGui.QCheckBox(self.frame_valid_vod)
        self.frame3_jes.setObjectName(_fromUtf8("frame3_jes"))
        self.gridLayout_3.addWidget(self.frame3_jes, 3, 0, 1, 1)
        self.frame3_assignation = QtGui.QCheckBox(self.frame_valid_vod)
        self.frame3_assignation.setObjectName(_fromUtf8("frame3_assignation"))
        self.gridLayout_3.addWidget(self.frame3_assignation, 6, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.frame_valid_vod)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.frame3_titre = QtGui.QCheckBox(self.groupBox_7)
        self.frame3_titre.setObjectName(_fromUtf8("frame3_titre"))
        self.verticalLayout_13.addWidget(self.frame3_titre)
        self.frame3_vod = QtGui.QCheckBox(self.groupBox_7)
        self.frame3_vod.setObjectName(_fromUtf8("frame3_vod"))
        self.verticalLayout_13.addWidget(self.frame3_vod)
        self.frame3_ratio = QtGui.QCheckBox(self.groupBox_7)
        self.frame3_ratio.setObjectName(_fromUtf8("frame3_ratio"))
        self.verticalLayout_13.addWidget(self.frame3_ratio)
        self.frame3_framerate = QtGui.QCheckBox(self.groupBox_7)
        self.frame3_framerate.setObjectName(_fromUtf8("frame3_framerate"))
        self.verticalLayout_13.addWidget(self.frame3_framerate)
        self.frame3_audio = QtGui.QCheckBox(self.groupBox_7)
        self.frame3_audio.setObjectName(_fromUtf8("frame3_audio"))
        self.verticalLayout_13.addWidget(self.frame3_audio)
        self.frame3_mixes = QtGui.QCheckBox(self.groupBox_7)
        self.frame3_mixes.setObjectName(_fromUtf8("frame3_mixes"))
        self.verticalLayout_13.addWidget(self.frame3_mixes)
        self.frame3_subs = QtGui.QCheckBox(self.groupBox_7)
        self.frame3_subs.setObjectName(_fromUtf8("frame3_subs"))
        self.verticalLayout_13.addWidget(self.frame3_subs)
        self.gridLayout_3.addWidget(self.groupBox_7, 7, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.frame_valid_vod)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.complete_lbl = QtGui.QLineEdit(self.frame_3)
        self.complete_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.complete_lbl.setReadOnly(True)
        self.complete_lbl.setObjectName(_fromUtf8("complete_lbl"))
        self.horizontalLayout_4.addWidget(self.complete_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.browse_btn = QtGui.QPushButton(self.frame_3)
        self.browse_btn.setObjectName(_fromUtf8("browse_btn"))
        self.horizontalLayout_2.addWidget(self.browse_btn)
        self.results_lbl = QtGui.QLineEdit(self.frame_3)
        self.results_lbl.setReadOnly(True)
        self.results_lbl.setObjectName(_fromUtf8("results_lbl"))
        self.horizontalLayout_2.addWidget(self.results_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.reset_btn = QtGui.QPushButton(self.frame_3)
        self.reset_btn.setObjectName(_fromUtf8("reset_btn"))
        self.horizontalLayout_3.addWidget(self.reset_btn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame_3)
        PackDCWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PackDCWindow)
        QtCore.QMetaObject.connectSlotsByName(PackDCWindow)

    def retranslateUi(self, PackDCWindow):
        PackDCWindow.setWindowTitle(_translate("PackDCWindow", "Packaging Double-Check", None))
        self.label_3.setText(_translate("PackDCWindow", "Operator", None))
        self.label.setText(_translate("PackDCWindow", "Workflow", None))
        self.frame1_assignation.setText(_translate("PackDCWindow", "Assignation de pistes", None))
        self.groupBox.setTitle(_translate("PackDCWindow", "Modulation", None))
        self.frame1_ordre.setText(_translate("PackDCWindow", "Ordre Pistes", None))
        self.frame1_peak.setText(_translate("PackDCWindow", "Peaking", None))
        self.frame1_24.setText(_translate("PackDCWindow", "24 bit", None))
        self.groupBox_3.setTitle(_translate("PackDCWindow", "Nomenclature", None))
        self.frame1_titre.setText(_translate("PackDCWindow", "Titre", None))
        self.frame1_ratio.setText(_translate("PackDCWindow", "Ratio", None))
        self.frame1_framerate.setText(_translate("PackDCWindow", "Framerate", None))
        self.frame1_audio.setText(_translate("PackDCWindow", "Langue Audio", None))
        self.frame1_mixes.setText(_translate("PackDCWindow", "Mixes", None))
        self.frame1_subs.setText(_translate("PackDCWindow", "Langue Subs", None))
        self.frame1_version.setText(_translate("PackDCWindow", "Version", None))
        self.frame1_prores.setText(_translate("PackDCWindow", "ProRes 422 HQ", None))
        self.frame1_tc.setText(_translate("PackDCWindow", "TC Original", None))
        self.frame1_mono.setText(_translate("PackDCWindow", "Pistes mono", None))
        self.groupBox_2.setTitle(_translate("PackDCWindow", "Video Scopes", None))
        self.frame1_valeurs.setText(_translate("PackDCWindow", "Valeurs noirs/blancs", None))
        self.frame1_colo.setText(_translate("PackDCWindow", "Colo ftr vs textless", None))
        self.frame1_23.setText(_translate("PackDCWindow", "23.98", None))
        self.frame1_jes.setText(_translate("PackDCWindow", "JES", None))
        self.frame1_prequal.setText(_translate("PackDCWindow", "Prequal", None))
        self.frame2_prores.setText(_translate("PackDCWindow", "ProRes 422 HQ", None))
        self.frame2_24.setText(_translate("PackDCWindow", "24 bit", None))
        self.frame2_tc.setText(_translate("PackDCWindow", "TC Original", None))
        self.frame2_jes.setText(_translate("PackDCWindow", "JES", None))
        self.groupBox_4.setTitle(_translate("PackDCWindow", "Modulation", None))
        self.frame2_ordre.setText(_translate("PackDCWindow", "Ordre Pistes", None))
        self.frame2_peak.setText(_translate("PackDCWindow", "Peaking", None))
        self.frame2_assignation.setText(_translate("PackDCWindow", "Assignation de pistes", None))
        self.groupBox_5.setTitle(_translate("PackDCWindow", "Nomenclature", None))
        self.frame2_titre.setText(_translate("PackDCWindow", "Titre", None))
        self.frame2_lib.setText(_translate("PackDCWindow", "Mention “lib”", None))
        self.frame2_ratio.setText(_translate("PackDCWindow", "Ratio", None))
        self.frame2_framerate.setText(_translate("PackDCWindow", "Framerate", None))
        self.frame2_audio.setText(_translate("PackDCWindow", "Langue Audio", None))
        self.frame2_mixes.setText(_translate("PackDCWindow", "Mixes", None))
        self.frame2_subs.setText(_translate("PackDCWindow", "Langue Subs", None))
        self.frame3_tc.setText(_translate("PackDCWindow", "TC 1h", None))
        self.frame3_mono.setText(_translate("PackDCWindow", "Pistes mono", None))
        self.frame3_24.setText(_translate("PackDCWindow", "24 bit", None))
        self.frame3_prores.setText(_translate("PackDCWindow", "ProRes 422 HQ", None))
        self.groupBox_6.setTitle(_translate("PackDCWindow", "Modulation", None))
        self.frame3_ordre.setText(_translate("PackDCWindow", "Ordre Pistes", None))
        self.frame3_peak.setText(_translate("PackDCWindow", "Peaking", None))
        self.frame3_jes.setText(_translate("PackDCWindow", "JES", None))
        self.frame3_assignation.setText(_translate("PackDCWindow", "Assignation de pistes", None))
        self.groupBox_7.setTitle(_translate("PackDCWindow", "Nomenclature", None))
        self.frame3_titre.setText(_translate("PackDCWindow", "Titre", None))
        self.frame3_vod.setText(_translate("PackDCWindow", "Mention “vod”", None))
        self.frame3_ratio.setText(_translate("PackDCWindow", "Ratio", None))
        self.frame3_framerate.setText(_translate("PackDCWindow", "Framerate", None))
        self.frame3_audio.setText(_translate("PackDCWindow", "Langue Audio", None))
        self.frame3_mixes.setText(_translate("PackDCWindow", "Mixes", None))
        self.frame3_subs.setText(_translate("PackDCWindow", "Langue Subs", None))
        self.label_2.setText(_translate("PackDCWindow", "Save report", None))
        self.browse_btn.setText(_translate("PackDCWindow", "Browse...", None))
        self.reset_btn.setText(_translate("PackDCWindow", "Reset", None))

